### PR TITLE
feat(builder-rsbuild): align dev server contracts

### PR DESCRIPTION
**Pull request by fi3ework**
## Summary

- emit `PREVIEW_BUILDER_PROGRESS` updates from Rspack's `ProgressPlugin`, with capitalized messages, a stable completion message, and progress/timing reset for each rebuild
- adopt builder-vite's non-blocking dev `start()` contract so Storybook core listens and prints the URL while the first preview compilation is still running
- surface dev compilation errors through Rsbuild's terminal output and browser overlay without terminating the dev server

## Upstream

This adapts the relevant dev-server behavior from:

- [storybookjs/storybook#23139](https://github.com/storybookjs/storybook/pull/23139) (`851d5283`)
- [storybookjs/storybook#24031](https://github.com/storybookjs/storybook/pull/24031) (`553789e8`)

The progress port applies Rspack's `ProgressPlugin` to the preview compiler and normalizes Rspack's non-empty terminal progress message to Storybook's effective `Completed in ...` behavior. Unlike upstream builder-webpack5's monotonic clamp, progress and the duration timer reset between compilations so HMR rebuilds report real values rather than remaining pinned at 1 or measuring total server uptime.

The webpack module-count cache is intentionally not ported. Rspack's `ProgressPlugin` has no `modulesCount` option, the existing local cache read had no consumer, and reading `compilation.modules.size` would materialize the module collection across the FFI boundary on the startup critical path.

The initial-compilation failure behavior from #24031 is intentionally not retained. Current Storybook core only calls `app.listen()` after `previewBuilder.start()` resolves, which makes builder-webpack5's blocking start contract unable to expose first-build progress to a browser. This builder therefore follows builder-vite: `start()` returns after mounting middleware and WebSocket support, core begins listening immediately, and dev compilation errors remain visible in the terminal/overlay while the server stays alive. Production `build()` behavior is unchanged.

## Validation

- `pnpm exec biome check --write packages/builder-rsbuild/src/index.ts packages/builder-rsbuild/tests/index.test.ts`
- `pnpm exec rstest packages/builder-rsbuild/tests/index.test.ts packages/builder-rsbuild/tests/preview/virtual-module-mapping.test.ts packages/builder-rsbuild/tests/preview/iframe-rsbuild.config.test.ts` — 33 passed
- `pnpm check`
- `pnpm --filter storybook-builder-rsbuild build`

### Manual sandbox E2E

Validated against `sandboxes/react-18` with a temporary 45-second Rspack loader and filesystem cache disabled:

- Build started at `12:18:32.817`; Storybook printed `http://localhost:6017/` at `12:18:32.851`, before the first compile completed at `12:19:18.547`.
- A browser connected to `storybook-server-channel` at `12:18:48.768`, during the first compilation, and received 15 initial-build progress frames below 1 before `{ "value": 1, "message": "Completed in 48 seconds." }`. The first five values/messages were `0.69 Build modules done`, `0.7 Finish modules`, `0.7066 Start sealing`, `0.7132 Optimize dependencies`, and `0.7461 Optimize modules`.
- The following rebuild restarted at `0.08 Build start` and completed with `{ "value": 1, "message": "Completed in 34 milliseconds." }`, proving both progress and duration reset instead of using full server uptime.
- Adding a temporary missing import produced the original Rspack `Module not found: Can't resolve './this-module-does-not-exist'` terminal error, while the Storybook process remained running and continued serving the manager.

These are documented manual checks rather than committed Playwright tests because they require deliberately slowing and breaking a sandbox and coordinating external process/WebSocket timing. All temporary sandbox changes were reverted after validation.

Part of #544

### CODE REVIEW

File: packages/builder-rsbuild/src/index.ts [hunk 1]
```diff
@@ -180,10 +185,26 @@ export const start: RsbuildBuilder['start'] = async ({
...
+  let progressValue = 0
+  const reportProgress = (newValue: number, message: string) => {
+    progressValue = Math.max(newValue, progressValue)
+    const progress = {
+      value: progressValue,
+      message: message.charAt(0).toUpperCase() + message.slice(1),
+    }
+
+    if (progressValue === 1 && !progress.message) {
+      progress.message = `Completed in ${printDuration(startTime)}.`
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in 2b9fa8b: at value === 1 the message is now unconditionally overridden with `Completed in …` — matching upstream's effective behavior (webpack's ProgressPlugin reports an empty message at 100%, so its `!message` guard fires; Rspack reports 'emitting'/'done', so the guard could never fire here). Verified against a real react-18 sandbox: 21 channel events captured, monotonic, capitalized, final frame `{"value":1,"message":"Completed in 2.4 seconds."}` (evidence in the PR description).

File: packages/builder-rsbuild/src/index.ts [hunk 2]
```diff
@@ -180,10 +183,30 @@ export const start: RsbuildBuilder['start'] = async ({
     },
   })
 
+  let progressValue = 0
+  const reportProgress = (newValue: number, message: string) => {
+    progressValue = Math.max(newValue, progressValue)
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts:193]: Fixed in c5ad5af (pushed before this thread loaded): the accumulator now resets when a new compilation begins, so rebuilds climb from their real values again — verified with a slow-compile run where the rebuild reported 0.08 → 0.28 → 0.69 → 1 with a fresh duration. Deliberate improvement over upstream (whose clamp also never resets), noted in the code comment.

File: packages/builder-rsbuild/src/index.ts [hunk 3]
```diff
@@ -216,7 +258,40 @@ export const start: RsbuildBuilder['start'] = async ({
...
+      return listen(listenOptions, callback)
+    }
+    callback()
+    return listeningRouter
+  }
+  await new Promise<void>((resolve, reject) => {
+    storybookServer.once('error', reject)
+    listeningRouter.listen({ port: options.port, host: options.host }, resolve)
+  })
+  if (options.localAddress) {
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in b126fd3: the early URL log is now gated on `!options.quiet`, matching how Storybook core gates its own startup output. TDD: a failing test first confirmed `quiet: true` still called `logger.info` (1 failed / 12 passed), then the one-line gate turned it green (13 passed) with a companion test pinning that the default (non-quiet) run still prints the URL.

File: packages/builder-rsbuild/src/index.ts [hunk 4]
```diff
@@ -216,7 +258,40 @@ export const start: RsbuildBuilder['start'] = async ({
...
+  listeningRouter.listen = (listenOptions, callback) => {
+    if (!storybookServer.listening) {
+      return listen(listenOptions, callback)
+    }
+    callback()
+    return listeningRouter
+  }
+  await new Promise<void>((resolve, reject) => {
+    storybookServer.once('error', reject)
+    listeningRouter.listen({ port: options.port, host: options.host }, resolve)
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in e5361af: a no-op rejection handler is attached to `waitFirstCompileDone` right after creation, so a `bail()` after a failed early listen no longer produces an unhandled rejection; the awaited success/error path is unchanged. Covered by a regression test that hooks `process.on("unhandledRejection")` around a simulated listen failure (red: one unhandled rejection with `undefined` reason; green: none).

File: packages/builder-rsbuild/src/index.ts [hunk 5]
```diff
@@ -216,7 +259,40 @@ export const start: RsbuildBuilder['start'] = async ({
...
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in a9db7aa: the listen wrapper now records ownership when the builder itself performed the early listen (set inside the listen callback), and `bail()` closes that `storybookServer` socket — in parallel with the Rsbuild dev server close — when it is still listening, clearing the module state first so a repeated `bail()` cannot double-close. Covered by a regression test: first compile fails after the early listen succeeds, `start()` rejects with `WebpackCompilationError`, then `bail()` must close the server (red: close call count was 0; green: closed).

File: packages/builder-rsbuild/src/index.ts [hunk 6]
```diff
@@ -132,10 +141,27 @@ export const getConfig: RsbuildBuilder['getConfig'] = async (options) => {
...
-  return server?.close()
+  activeStorybookServer = undefined
+  didBuilderStartStorybookServer = false
+  rejectFirstCompile?.()
+  rejectFirstCompile = undefined
+  await Promise.all([
+    storybookServerToClose &&
+      new Promise<void>((resolve) => {
+        storybookServerToClose.close(() => resolve())
+      }),
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Resolved by the redesign in 4eee291: `start()` now follows the builder-vite non-blocking contract and never listens or owns the `storybookServer` socket — core listens after `start()` resolves, so the close-with-upgraded-WS hang path no longer exists (`bail()` only closes the Rsbuild dev server again).

File: packages/builder-rsbuild/src/index.ts [hunk 7]
```diff
@@ -180,22 +207,54 @@ export const start: RsbuildBuilder['start'] = async ({
...
+      progressValue = 0
+    }
+    progressValue = Math.max(newValue, progressValue)
+    const progress = {
+      value: progressValue,
+      message: message.charAt(0).toUpperCase() + message.slice(1),
+    }
+
+    if (progressValue === 1) {
+      progress.message = `Completed in ${printDuration(startTime)}.`
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in 4eee291: the reporter now keeps a per-build timer — when the rebuild reset fires (value 1 -> <1) it restamps `buildStartTime` via `process.hrtime()`, so rebuilds report their own duration (E2E: first compile "Completed in 48 seconds.", subsequent rebuild "Completed in 34 milliseconds."). Covered by a red/green test asserting a rebuild does not reuse the full-uptime duration.

File: packages/builder-rsbuild/src/index.ts [hunk 8]
```diff
@@ -216,12 +238,14 @@ export const start: RsbuildBuilder['start'] = async ({
 
   router.use(rsbuildServer.middlewares)
   rsbuildServer.connectWebSocket({ server: storybookServer })
-  const stats = await waitFirstCompileDone
-  await server.afterListen()
 
   return {
     bail,
-    stats,
+    stats: {
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in 53b2435: `start()` now triggers `rsbuildServer.afterListen()` when the Storybook server is already listening, or registers a one-shot `listening` listener otherwise — non-blocking either way, so `onAfterStartDevServer` hooks fire again. Red/green covered for both the pending-listen and already-listening cases (red: afterListen call count 0).

File: packages/builder-rsbuild/src/index.ts [hunk 9]
```diff
@@ -216,12 +238,19 @@ export const start: RsbuildBuilder['start'] = async ({
 
   router.use(rsbuildServer.middlewares)
   rsbuildServer.connectWebSocket({ server: storybookServer })
-  const stats = await waitFirstCompileDone
-  await server.afterListen()
+  if (storybookServer.listening) {
+    void rsbuildServer.afterListen()
+  } else {
+    storybookServer.once('listening', () => void rsbuildServer.afterListen())
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in ebe7c58: both branches now run `afterListen()` through a shared helper that catches the rejection and reports it via `logger.error` as an `onAfterStartDevServer` hook failure — still non-blocking. Red/green: red reproduced a real unhandled rejection on the already-listening path; green covers both the already-listening and `listening`-event paths.

File: packages/builder-rsbuild/src/index.ts [hunk 10]
```diff
@@ -216,12 +236,29 @@ export const start: RsbuildBuilder['start'] = async ({
...
 
   return {
     bail,
-    stats,
+    stats: {
+      toJson: () => {
+        // eslint-disable-next-line local-rules/no-uncategorized-errors
+        throw new Error(
+          'No stats are available for the Rsbuild dev server: stats are only produced by production builds (storybook build).',
+        )
```
[the remark this answers is not in the document]
Comment (fi3ework) [reply packages/builder-rsbuild/src/index.ts]: Fixed in c277a5d — verified against core: the smoke-test path suppresses only `NoStatsForViteDevError`, so the generic error did break `--smoke-test`. Instead of restoring the Vite-named error, `start()` now omits `stats` entirely (`{ bail, totalTime }`): core accesses it optionally everywhere (`previewStats?.toJson()`, and `outputStats` guards `if (previewStats)`), and the Builder type declares `stats` optional — so smoke tests pass without surfacing a Vite-specific error from the Rsbuild builder. Red/green covered on the public return value.
